Use CALLCENTER_DB

Select * From Clientes
Select ID, NOMBRE, APELLIDO, DNI,IDDIRECCION, EMAIL, TELEFONO, FECHANACIMIENTO From Clientes
select * from incidentes
Select ID, IDEMPLEADO, IDCLIENTE, FECHA_INICIO, FECHA_CIERRE, DETALLES, IDESTADO, COMENTARIOFINAL From Incidentes
Select ID, NOMBREUSUARIO, CONTRASEÑA, NOMBRE, IDCARGO, APELLIDO, DNI, IDDIRECCION, EMAIL, TELEFONO, FECHANACIMIENTO From Empleados

Insert Into Clientes(NOMBRE, APELLIDO, DNI,IDDIRECCION, EMAIL, TELEFONO, FECHANACIMIENTO)
Values(@NOMBRE, @APELLIDO, @DNI, @IDDIRECCION, @EMAIL, @TELEFONO, @FECHANACIMIENTO)

Update Incidentes set IDEMPLEADO = @IDEMPLEADO, IDCLIENTE = @IDCLIENTE, FECHA_INICIO = '2021/01/02', FECHA_CIERRE = getDate(), DETALLES = @DETALLES, IDESTADO = @IDESTADO, COMENTARIOFINAL = @COMENTARIOFINAL Where ID = " + nuevo.ID + "

Use CALLCENTER_DB
Select * From Clientes

Update Clientes(NOMBRE, APELLIDO, DNI, IDDIRECCION, EMAIL, TELEFONO, FECHANACIMIENTO) VALUES(