Use CALLCENTER_DB

Select * From Clientes
Select ID, NOMBRE, APELLIDO, DNI,IDDIRECCION, EMAIL, TELEFONO, FECHANACIMIENTO From Clientes
select * from incidentes
Select ID, IDEMPLEADO, IDCLIENTE, FECHA_INICIO, FECHA_CIERRE, DETALLES, IDESTADO, COMENTARIOFINAL From Incidentes
Select ID, NOMBREUSUARIO, CONTRASEÑA, NOMBRE, IDCARGO, APELLIDO, DNI, IDDIRECCION, EMAIL, TELEFONO, FECHANACIMIENTO From Empleados